"""
Export utilities for DecisionGuide results
"""
from datetime import datetime
from io import BytesIO
import json

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER


def export_to_json(tree_title, decision, explanation, path, timestamp=None):
    """
    Export assessment result to JSON format
    """
    if timestamp is None:
        timestamp = datetime.now().isoformat()
    
    data = {
        "assessment": tree_title,
        "timestamp": timestamp,
        "decision": decision,
        "explanation": explanation,
        "path": path
    }
    
    return json.dumps(data, indent=2)


def export_to_text(tree_title, decision, explanation, path, timestamp=None):
    """
    Export assessment result to plain text format
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    text = f"""
DecisionGuide Assessment Report
{'=' * 50}

Assessment: {tree_title}
Date: {timestamp}

DECISION
{'-' * 50}
Decision Code: {decision}

EXPLANATION
{'-' * 50}
{explanation}

DECISION PATH
{'-' * 50}
"""
    
    for i, step in enumerate(path, 1):
        text += f"{i}. {step}\n"
    
    text += f"\n{'=' * 50}\n"
    text += "Generated by DecisionGuide\n"
    text += "https://github.com/Adeshola3/DecisionGuide\n"
    
    return text


def export_to_pdf(tree_title, decision, explanation, path, timestamp=None):
    """
    Export assessment result to PDF format
    Returns bytes buffer containing the PDF
    """
    if timestamp is None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                           rightMargin=72, leftMargin=72,
                           topMargin=72, bottomMargin=18)
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    elements.append(Paragraph("DecisionGuide Assessment Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Assessment info table
    info_data = [
        ['Assessment:', tree_title],
        ['Date:', timestamp],
        ['Decision Code:', decision]
    ]
    
    info_table = Table(info_data, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecf0f1')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    elements.append(info_table)
    elements.append(Spacer(1, 20))
    
    # Explanation section
    elements.append(Paragraph("Explanation", heading_style))
    elements.append(Paragraph(explanation, styles['BodyText']))
    elements.append(Spacer(1, 20))
    
    # Decision path section
    elements.append(Paragraph("Decision Path", heading_style))
    
    path_data = [[str(i), step] for i, step in enumerate(path, 1)]
    
    path_table = Table(path_data, colWidths=[0.5*inch, 5.5*inch])
    path_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#ecf0f1')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (0, -1), 'CENTER'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    elements.append(path_table)
    elements.append(Spacer(1, 30))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    
    elements.append(Paragraph("Generated by DecisionGuide", footer_style))
    elements.append(Paragraph("https://github.com/Adeshola3/DecisionGuide", footer_style))
    
    # Build PDF
    doc.build(elements)
    
    buffer.seek(0)
    return buffer


def get_filename(tree_title, format_type):
    """
    Generate a filename for export
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = tree_title.replace(" ", "_").replace("/", "-")
    
    extension = {
        'pdf': 'pdf',
        'json': 'json',
        'txt': 'txt'
    }.get(format_type, 'txt')
    
    return f"DecisionGuide_{safe_title}_{timestamp}.{extension}"